# Post-install hook (Windows): create the standalone CLI shim so
# `herdr-auto-update check` works from a console right after
# `herdr plugin install`. herdr runs [[build]] commands at install time;
# this one compiles nothing - it writes a .cmd shim into the user-writable
# %LOCALAPPDATA%\Microsoft\WindowsApps dir (on the Windows PATH).
#
# The .cmd is NOT a static path to the plugin root: herdr builds from a
# temporary checkout and moves the plugin afterwards, so the shim resolves
# the launcher at run time via `herdr plugin list --json` (manifest_path).
# Best-effort and silent: never fails the install.

$ErrorActionPreference = "SilentlyContinue"

if (-not $env:LOCALAPPDATA) { exit 0 }
$shimDir = Join-Path $env:LOCALAPPDATA "Microsoft\WindowsApps"
$shim = Join-Path $shimDir "herdr-auto-update.cmd"

$content = @"
@echo off
rem herdr-auto-update CLI shim (generated by scripts/install-cli-shim.ps1).
rem Resolves the plugin launcher at run time; remove when uninstalling.
powershell -NoProfile -ExecutionPolicy Bypass -Command "`$p = (herdr plugin list --json | ConvertFrom-Json).result.plugins | Where-Object { `$_.plugin_id -eq 'herdr-auto-update' } | Select-Object -First 1; if (`$p -and `$p.manifest_path) { `$l = Join-Path (Split-Path -Parent `$p.manifest_path) 'bin\herdr-auto-update.ps1'; if (Test-Path `$l) { & powershell -NoProfile -ExecutionPolicy Bypass -File `$l @args; exit `$LASTEXITCODE } }; Write-Error 'herdr-auto-update: plugin launcher not found (is the plugin installed?)'; exit 1" %*
"@

try {
    if (-not (Test-Path $shimDir)) { New-Item -ItemType Directory -Path $shimDir -Force | Out-Null }
    [System.IO.File]::WriteAllText($shim, $content)
} catch {}

exit 0
