#!/bin/sh
# Post-install hook: put the standalone CLI on the user's PATH so
# `herdr-auto-update check` works from a shell right after
# `herdr plugin install`. herdr runs [[build]] commands at install time;
# this one compiles nothing - it writes a self-resolving launcher shim into
# the user's bin dir.
#
# The shim is deliberately NOT a symlink to the plugin root: herdr builds
# from a temporary checkout (.tmp-install-*/checkout) and moves the plugin to
# its final directory afterwards, so a symlink created here would dangle. The
# script shim resolves the plugin root at run time - the stable-hash glob
# first, then `herdr plugin list --json` as the authoritative fallback - so
# it survives reinstalls, temp checkouts, and custom HERDR_PLUGIN_ROOT.
#
# Best-effort and silent: exits 0 even when the shim cannot be written, so
# install never fails over a convenience. `herdr plugin uninstall` leaves the
# shim behind for the user to remove (documented in the README).

set -eu

if [ -z "${XDG_BIN_HOME:-}" ] && [ -z "${HOME:-}" ]; then
    exit 0
fi
shim_dir=${XDG_BIN_HOME:-"$HOME/.local/bin"}
SHIM="$shim_dir/herdr-auto-update"

mkdir -p "$shim_dir" 2>/dev/null || exit 0

# A previous install may have left a dangling symlink here (v1.0.6 wrote a
# symlink to a temp checkout that herdr later moved away); `cat >` would
# follow it and fail, so clear it first.
rm -f "$SHIM" 2>/dev/null || true

cat > "$SHIM" <<'SHIM_EOF'
#!/bin/sh
# herdr-auto-update CLI shim (generated by scripts/install-cli-shim.sh).
# Resolves the plugin launcher at run time so it survives reinstalls and
# install-time temp checkouts. Remove this file when uninstalling the plugin.
set -eu
launcher=
for d in "$HOME/.config/herdr/plugins/github/"/herdr-auto-update-*/; do
    if [ -f "$d/bin/herdr-auto-update" ]; then
        launcher="$d/bin/herdr-auto-update"
        break
    fi
done
if [ -z "$launcher" ] && command -v herdr >/dev/null 2>&1; then
    for p in $(herdr plugin list --json 2>/dev/null | grep -o '"manifest_path":"[^"]*"' | cut -d'"' -f4 || true); do
        case "$p" in
            */herdr-auto-update/herdr-plugin.toml|*/herdr-auto-update-*/herdr-plugin.toml)
                if [ -f "${p%/herdr-plugin.toml}/bin/herdr-auto-update" ]; then
                    launcher="${p%/herdr-plugin.toml}/bin/herdr-auto-update"
                    break
                fi
                ;;
        esac
    done
fi
if [ -z "$launcher" ]; then
    echo "herdr-auto-update: plugin launcher not found (is the plugin installed?)" >&2
    exit 1
fi
exec "$launcher" "$@"
SHIM_EOF

chmod +x "$SHIM" 2>/dev/null || true

exit 0
