# Post-install hook (Windows): create the standalone CLI shim so
# `herdr-auto-update check` works from a console right after
# `herdr plugin install`. herdr runs [[build]] commands at install time;
# this one compiles nothing - it writes two files into the user-writable
# %LOCALAPPDATA%\Microsoft\WindowsApps dir (on the Windows PATH):
#
#   herdr-auto-update.cmd      thin entry point
#   herdr-auto-update.ps1      resolver
#
# The resolver locates the plugin launcher at run time via
# `herdr plugin list --json` (manifest_path) and forwards all arguments with
# `@args`. It is deliberately a -File script, NOT a `-Command "string"`
# one-liner: with -Command, trailing arguments are concatenated into the
# command string and parsed as code (`herdr-auto-update update` became
# `...; exit 1 update` and died with a ParserError in v1.0.8).
#
# The plugin list is captured via `cmd /c` redirection and decoded by BOM so
# herdr's Windows pipe output (which may be UTF-16LE - see registry.rs
# decode_stdout) cannot corrupt the JSON parse.
# Best-effort and silent: never fails the install.

$ErrorActionPreference = "SilentlyContinue"

if (-not $env:LOCALAPPDATA) { exit 0 }
$shimDir = Join-Path $env:LOCALAPPDATA "Microsoft\WindowsApps"
$cmd = Join-Path $shimDir "herdr-auto-update.cmd"
$resolver = Join-Path $shimDir "herdr-auto-update.ps1"

$resolverBody = @"
# herdr-auto-update CLI shim resolver (generated by scripts/install-cli-shim.ps1).
# Resolves the plugin launcher at run time and forwards all arguments.
# Remove this file and herdr-auto-update.cmd when uninstalling the plugin.
try {
    `$tmp = Join-Path `$env:TEMP ("hau-list-" + [guid]::NewGuid().ToString("N") + ".json")
    & cmd.exe /c "herdr plugin list --json > `"`$tmp`""
    `$bytes = [System.IO.File]::ReadAllBytes(`$tmp)
    if (`$bytes.Length -ge 2 -and `$bytes[0] -eq 0xFF -and `$bytes[1] -eq 0xFE) {
        `$text = [System.Text.Encoding]::Unicode.GetString(`$bytes, 2, `$bytes.Length - 2)
    } elseif (`$bytes.Length -ge 3 -and `$bytes[0] -eq 0xEF -and `$bytes[1] -eq 0xBB -and `$bytes[2] -eq 0xBF) {
        `$text = [System.Text.Encoding]::UTF8.GetString(`$bytes, 3, `$bytes.Length - 3)
    } else {
        `$text = [System.Text.Encoding]::UTF8.GetString(`$bytes)
    }
    Remove-Item `$tmp -ErrorAction SilentlyContinue
    `$p = (`$text | ConvertFrom-Json).result.plugins | Where-Object { `$_.plugin_id -eq 'herdr-auto-update' } | Select-Object -First 1
    if (`$p -and `$p.manifest_path) {
        `$l = Join-Path (Split-Path -Parent `$p.manifest_path) 'bin\herdr-auto-update.ps1'
        if (Test-Path `$l) {
            & powershell -NoProfile -ExecutionPolicy Bypass -File `$l @args
            exit `$LASTEXITCODE
        }
    }
} catch {
    # fall through to the not-found error
}
Write-Error 'herdr-auto-update: plugin launcher not found (is the plugin installed?)'
exit 1
"@

$cmdBody = @"
@echo off
rem herdr-auto-update CLI shim (generated by scripts/install-cli-shim.ps1).
rem Remove when uninstalling the plugin.
powershell -NoProfile -ExecutionPolicy Bypass -File "$resolver" %*
"@

try {
    if (-not (Test-Path $shimDir)) { New-Item -ItemType Directory -Path $shimDir -Force | Out-Null }
    [System.IO.File]::WriteAllText($resolver, $resolverBody)
    [System.IO.File]::WriteAllText($cmd, $cmdBody)
} catch {}

exit 0
